name: Build Documentation

on:
  push:
    branches:
      - main


jobs:
  build:
    uses: huggingface/doc-builder/.github/workflows/build_main_documentation.yml@main
    with:
      commit_sha: ${{ github.sha }}
      package: ml-for-3d-course
      package_name: ml-for-3d-course
      path_to_docs: ml-for-3d-course/units/
      additional_args: --not_python_module --latex
      languages: en
    secrets:
      token: ${{ secrets.HUGGINGFACE_PUSH }}
      hf_token: ${{ secrets.HF_DOC_BUILD_PUSH }}
